language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
before_install:
  - rvm install 2.2.2
  - rvm use 2.2.2
jdk:
  - oraclejdk7
  - openjdk7
script:
  - mvn clean install -Pqulice --batch-mode --errors
